// <auto-generated />
using System;
using Crudblazorserve2;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Crudblazorserve2.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CautionSououmission.Shared.Beneficiaire", b =>
                {
                    b.Property<int>("Id_beneficiaire")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id_beneficiaire"));

                    b.Property<string>("designation_beneficiaire")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("libelle_projet")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("telephone1")
                        .HasColumnType("integer");

                    b.Property<int>("telephone2")
                        .HasColumnType("integer");

                    b.HasKey("Id_beneficiaire");

                    b.ToTable("Beneficiaires");
                });

            modelBuilder.Entity("CautionSououmission.Shared.Caution", b =>
                {
                    b.Property<int>("idcaution")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("idcaution"));

                    b.Property<string>("addressbene")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("addresscli")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("article")
                        .HasColumnType("integer");

                    b.Property<string>("bpbene")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("bpcli")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("codepaysbene")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("codepayscli")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("datecaution")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("devise")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("emailbene")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("emailcli")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("libbeneficiaire")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("montant")
                        .HasColumnType("double precision");

                    b.Property<string>("montantlettre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("numappeloffre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("numcaution")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("numrccli")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("projetbeneficiaire")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("raisonsocialecli")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("tel1bene")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("tel2bene")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("telephone1cli")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("telephone2cli")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("travaux")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("idcaution");

                    b.ToTable("Cautions");
                });

            modelBuilder.Entity("CautionSououmission.Shared.Donneurordre", b =>
                {
                    b.Property<int>("id_client")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id_client"));

                    b.Property<string>("bp")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("num_registre_commerce")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("raison_sociale")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("telephone1")
                        .HasColumnType("integer");

                    b.Property<int>("telephone2")
                        .HasColumnType("integer");

                    b.HasKey("id_client");

                    b.ToTable("Donneurordres");
                });

            modelBuilder.Entity("CautionSououmission.Shared.Typearticle", b =>
                {
                    b.Property<int>("id_article")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id_article"));

                    b.Property<string>("libelle_article")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id_article");

                    b.ToTable("Typearticles");
                });
#pragma warning restore 612, 618
        }
    }
}
